version: '3'

services:
  gnps-datasetcache-web:
    build: .
    ports:
      - "5234:5000"
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./logs/:/app/logs
    networks:
      - default
      - nginx-net
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: gnps-datasetcache.ucsd.edu
      VIRTUAL_PORT: 5234
      LETSENCRYPT_HOST: gnps-datasetcache.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    

  gnps-datasetcache-beat:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
    networks:
      - default
      - nginx-net
    command: /app/run_worker_beat.sh

  gnps-datasetcache-worker:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
    networks:
      - default
      - nginx-net
    command: /app/run_worker_compute.sh
    
  gnps-datasetcache-redis:
    image: redis
    networks:
      - default

  gnps-datasetcache-datasette:
    ports:
      - "5235:8001"
    image: datasetteproject/datasette
    depends_on:
      - "gnps-datasetcache-web"
    volumes:
      - ./database/:/app/database:ro
    networks:
      - nginx-net
      - default
    restart: on-failure
    command: datasette -p 8001 -h 0.0.0.0 --setting base_url /datasette/ --setting max_returned_rows 50000 --setting sql_time_limit_ms 10000 --setting max_csv_mb 0 /app/database/database.db

networks:
  nginx-net:
    external:
      name: nginx-net