version: '3'

services:
  gnps-datasetcache-web:
    build: .
    ports:
      - "5234:5000"
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./logs/:/app/logs
    networks:
      - default
      - nginx-net
    command: /app/run_server.sh
    

  gnps-datasetcache-worker:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
    networks:
      - default
      - nginx-net
    command: /app/run_worker_compute.sh
    
  redis:
    image: redis
    networks:
      - default

  datasette:
    ports:
      - "5235:8001"
    image: datasetteproject/datasette
    volumes:
      - ./database/:/app/database:ro
    networks:
      - nginx-net
      - default
    command: datasette -p 8001 -h 0.0.0.0 --setting base_url /datasette/ --setting max_returned_rows 50000 /app/database/database.db

networks:
  nginx-net:
    external:
      name: nginx-net