version: '3'

services:
  gnps-datasetcache-web:
    build: .
    ports:
      - "5234:5000"
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./logs/:/app/logs
    networks:
      - default
      - nginx-net
    command: /app/run_server.sh
    

  gnps-datasetcache-worker:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
    networks:
      - default
      - nginx-net
    command: /app/run_worker_compute.sh
    
  redis:
    image: redis
    networks:
      - default

networks:
  nginx-net:
    external:
      name: nginx-net