version: '3'

services:
  gnps-datasetcache-web:
    build: .
    ports:
      - "5234:5000"
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./workflows/:/app/workflows:ro
      - ./logs/:/app/logs
    networks:
      - default
      - nginx-net
    restart: always
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: datasetcache.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: datasetcache.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
  
  # This does 
  gnps-datasetcache-beat:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./workflows/:/app/workflows
      - .env:/app/.env
    networks:
      - default
      - nginx-net
    restart: always
    command: /app/run_worker_beat.sh

  gnps-datasetcache-worker:
    build: .
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./workflows/:/app/workflows
      - .env:/app/.env
    networks:
      - default
      - nginx-net
    restart: always
    command: /app/run_worker_compute.sh
    deploy:
      resources:
        limits:
          memory: 64G

  gnps-datasetcache-conversion:
    # update build to use different docker file
    build:
      context: .
      dockerfile: Dockerfile.conversion
    volumes:
      - ./database/:/app/database
      - ./temp/:/app/temp
      - ./workflows/:/app/workflows
      - .env:/app/.env
    networks:
      - default
      - nginx-net
    restart: always
    command: /app/run_worker_conversion.sh

  gnps-datasetcache-worker-datasetsummary:
    container_name: gnps-datasetcache-worker-datasetsummary
    build:
      context: .
    volumes:
      - ./workflows/:/app/workflows
      - /data/datasets:/data/datasets
      - ./gscratch:/data/gscratch
    networks:
      - default
    restart: always
    command: /app/run_worker_datasetsummary.sh
    deploy:
      resources:
        limits:
          memory: 32G
          cpus: 8
    
  gnps-datasetcache-redis:
    image: valkey/valkey:alpine3.20
    restart: always
    networks:
      - default

  gnps-datasetcache-datasette:
    ports:
      - "5235:5234" # This port selection of the internal port matching the external port of the web server is to get around a datasette bug
    image: datasetteproject/datasette:0.64.6
    depends_on:
      - "gnps-datasetcache-web"
    volumes:
      - ./database/:/app/database:ro
      - ./run_datasette.sh:/app/run_datasette.sh
    networks:
      - nginx-net
      - default
    restart: always
    command: /app/run_datasette.sh
    environment:
      VIRTUAL_HOST: datasetcachedatasette.gnps2.org
      VIRTUAL_PORT: 5234
      LETSENCRYPT_HOST: datasetcachedatasette.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

  gnps-datasetcache-datasette2:
    ports:
      - "5236:5234" # This port selection of the internal port matching the external port of the web server is to get around a datasette bug
    image: datasetteproject/datasette:0.64.6
    depends_on:
      - "gnps-datasetcache-web"
    volumes:
      - ./database/:/app/database:ro
      - ./run_datasette.sh:/app/run_datasette.sh
    networks:
      - nginx-net
      - default
    restart: always
    command: /app/run_datasette.sh

networks:
  nginx-net:
    external:
      name: nginx-net