channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - pandas
  - pip
  - pip:
      - xmltodict
      - requests
      - vladiate
      - bs4
      - lxml
      - tqdm
      - owlready2
      - massql
      - networkx
